declare module 'react-back-to-top'
declare module 'react-date-range/dist/defaultRanges'
declare module 'react-date-range'
declare module 'react-modal-video'
declare module 'react-currency-masked-input'
